services:
  - type: web
    name: funseek-shipment
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: funseek-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: funseek-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: funseek-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: funseek-db
          property: database
      - key: DB_PORT
        fromDatabase:
          name: funseek-db
          property: port
      - key: R2_ENABLED
        value: true
      - key: R2_ENDPOINT
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_PUBLIC_URL
        sync: false
      - key: JWT_SECRET
        sync: false


databases:
  - name: funseek-db
    region: singapore
    databaseName: funseek
    user: postgres
